import { UserRole } from "../enum/enum";

export type PermissionsInterface = {
    [key in UserRole]: Partial<PermissionsDataInterface>;
} & {
    default: Partial<PermissionsDataInterface>;
};
export interface PermissionsDataInterface {
    'audit:read': boolean;
    'project:link:read': boolean;
    'project:link:write': boolean;
    'project:create': boolean;
    'project:read': boolean;
    'project:write': boolean;
    'project:update': boolean;
    'project:delete': boolean;
    'project:share:read': boolean;
    'project:share:write': boolean;
    'project:share:delete': boolean;
    'project:forceReload:write': boolean;
    'project:theme:write': boolean;
    'project:assets:read': boolean;
    'project:assets:write': boolean;
    'project:assets:delete': boolean;
    'project:duplicate': boolean;
    'element:read': boolean;
    'element:write': boolean;
    'element:lock:write': boolean;
    'elements:move': boolean;
    'element:syncedElement:create': boolean;
    'element:syncedElement:delete': boolean;
    'systemLogs:read': boolean;
    'settings:view': boolean;
    'settings:user:read:all': boolean;
    'settings:user:read': boolean;
    'settings:user:write': boolean;
    'settings:user:delete': boolean;
    'settings:clients:read': boolean;
    'settings:clients:write': boolean;
    'settings:clients:delete': boolean;
    'settings:projects:read': boolean;
    'settings:projects:write': boolean;
    'settings:projects:delete': boolean;
    'settings:admin:read': boolean;
    'settings:admin:streamerAuditLogs:read': boolean;
    'settings:admin:elementManager:read': boolean;
    'settings:admin:elementManager:write': boolean;
    'settings:streamer:read': boolean;
    'settings:streamer:ownEditor:read': boolean;
    'settings:streamer:ownEditor:write': boolean;
    'settings:streamer:ownProjects:read': boolean;
    'settings:streamer:ownProjects:write': boolean;
    'settings:streamer:otherEditor:read': boolean;
    'settings:streamer:otherEditor:write': boolean;
    'settings:streamer:otherProjects:read': boolean;
    'settings:streamer:otherProjects:write': boolean;
    'liveblocks:auth': boolean;
    'project:obs:create': boolean;
    'project:obs:delete': boolean;
    'project:obs:sync': boolean;
    'project:obs:update': boolean;
    'client:editor:read:all': boolean;
    'client:editor:read': boolean;
    'client:editor:write': boolean;
    'client:editor:delete': boolean;
    'client:mngmt:write': boolean;
    'client:write': boolean;
    'element:custom:js': boolean;
    'system:ignoreMaintenance': boolean;
}
